name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Internet Connectivity
        run: |
          ping -c 4 github.com
          curl -I https://github.com/actions/upload-artifact

      - name: Verify Action Versions
        run: |
          curl -s https://api.github.com/repos/actions/upload-artifact/releases | jq -r '.[].tag_name'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          gem install xcpretty

      - name: Run Tests and Generate Allure Report
        run: ./generate_allure_report.sh

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Inspect Runner Actions Directory
        run: |
          ls -la /home/runner/work/_actions
