name: Debug Upload Artifact

on: [push, pull_request]

jobs:
  test-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Check Internet Connectivity
        run: |
          ping -c 4 github.com
          curl -I https://github.com/actions/upload-artifact

      - name: Check Action Versions
        run: |
          curl -s https://api.github.com/repos/actions/upload-artifact/releases | jq -r '.[].tag_name'

      - name: Create Test Report Directory
        run: |
          mkdir -p allure-report
          echo "Test report content" > allure-report/test.txt

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: allure-report
