name: Debug Upload Artifact

on: [push, pull_request]

jobs:
  test-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Runner Environment
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Temp Path: $RUNNER_TEMP"
          echo "Runner Tool Cache: $RUNNER_TOOL_CACHE"
          echo "GitHub Actions Version:"
          cat /usr/local/actions-runner/.env 2>/dev/null || echo "Runner version info not found"

      - name: Verify Access to Marketplace
        run: |
          curl -I https://github.com/actions/upload-artifact

      - name: Clear Cache
        run: rm -rf $RUNNER_TOOL_CACHE/actions

      - name: Create Test Report Directory
        run: |
          mkdir -p allure-report
          echo "Test report content" > allure-report/test.txt

      - name: Upload Test Report
        uses: actions/upload-artifact@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          name: test-report
          path: allure-report
